spring:
  application:
    name: gmao

  datasource:
    url: jdbc:h2:file:./data/gmao;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG