spring:
  application:
    name: gmao
  datasource:
    url: jdbc:mysql://localhost:3306/gmao
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ana0000YNS
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG